/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author s.lucas
 */
public class ProjetoGEscolar extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoGEscolar
     */
    public ProjetoGEscolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        lbBoletim = new javax.swing.JLabel();
        lbAluno2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbRNota1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbRNota2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbRNota3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbResultadoAluno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbResult = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbRMedia = new javax.swing.JLabel();
        lbRAluno = new javax.swing.JLabel();
        lbGEscolar = new javax.swing.JLabel();
        lbAluno = new javax.swing.JLabel();
        txtAluno = new javax.swing.JTextField();
        lbNota1 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        lbNota2 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        lbNota3 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        btGBoletim = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbBoletim.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbBoletim.setText("Boletim");

        lbAluno2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbAluno2.setText("Aluno");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nota 1:");

        lbRNota1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbRNota1.setText("???");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Nota 2:");

        lbRNota2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbRNota2.setText("???");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Nota 3:");

        lbRNota3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbRNota3.setText("???");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Média:");

        lbMedia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMedia.setText("???");

        lbResultado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbResultado.setText("Resultado");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("O aluno:");

        lbResultadoAluno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbResultadoAluno.setText("???");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("está");

        lbResult.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbResult.setText("???");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("com média");

        lbRMedia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbRMedia.setText("???");

        lbRAluno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbRAluno.setText("???");

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lbRNota3))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMedia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addComponent(lbAluno2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbRAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbResultado)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbRNota1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(lbResultadoAluno)
                                .addGap(26, 26, 26))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbRNota2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbResult)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel17)
                                .addGap(38, 38, 38)))
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRMedia)
                            .addComponent(jLabel15))
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBoletim)
                .addGap(241, 241, 241))
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbBoletim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAluno2)
                    .addComponent(jLabel3)
                    .addComponent(lbResultado)
                    .addComponent(lbRAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbRNota1)
                    .addComponent(jLabel13)
                    .addComponent(lbResultadoAluno)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbRNota2)
                    .addComponent(lbResult)
                    .addComponent(jLabel17)
                    .addComponent(lbRMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbRNota3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbMedia))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lbGEscolar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbGEscolar.setText("Gestor Escolar");

        lbAluno.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbAluno.setText("Aluno");

        txtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlunoActionPerformed(evt);
            }
        });

        lbNota1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbNota1.setText("Nota 1");

        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });

        lbNota2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbNota2.setText("Nota 2");

        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });

        lbNota3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbNota3.setText("Nota 3");

        btGBoletim.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btGBoletim.setText("Gerar Boletim");
        btGBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGBoletimActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(lbGEscolar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbNota1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(txtNota1))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbNota2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(txtNota2))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbNota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNota3)))
                                    .addComponent(lbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btGBoletim, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGEscolar)
                .addGap(18, 18, 18)
                .addComponent(lbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNota2)
                    .addComponent(lbNota3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtNota1)
                    .addComponent(txtNota2))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGBoletim, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void txtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlunoActionPerformed
        
    }//GEN-LAST:event_txtAlunoActionPerformed

    private void btGBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGBoletimActionPerformed
        String aluno;
        double n1, n2, n3, media;
        DecimalFormat f = new DecimalFormat("0.0");
        
        aluno = txtAluno.getText();
        n1 = Double.parseDouble(txtNota1.getText());
        n2 = Double.parseDouble(txtNota2.getText());
        n3 = Double.parseDouble(txtNota3.getText());
        media = (n1+n2+n3)/3;
        
        if(media>=7){
            lbResult.setText("Aprovado");
            lbRAluno.setText(aluno);
            lbResultadoAluno.setText(aluno);
            lbRNota1.setText(String.valueOf(n1));
            lbRNota2.setText(String.valueOf(n2));
            lbRNota3.setText(String.valueOf(n3));
            lbMedia.setText(String.valueOf(media));
            lbRMedia.setText(String.valueOf(media)); 
            Painel.setBackground(Color.green);
        }else{
            lbResult.setText("Reprovado");
            lbRAluno.setText(aluno);
            lbResultadoAluno.setText(aluno);
            lbRNota1.setText(String.valueOf(n1));
            lbRNota2.setText(String.valueOf(n2));
            lbRNota3.setText(String.valueOf(n3));
            lbMedia.setText(String.valueOf(media));
            lbRMedia.setText(String.valueOf(media));
            Painel.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_btGBoletimActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtAluno.setText(null);
        txtNota1.setText(null);
        txtNota2.setText(null);
        txtNota3.setText(null);
        lbRAluno.setText("???");
        lbRNota1.setText("???");
        lbRNota2.setText("???");
        lbRNota3.setText("???");
        lbMedia.setText("???");
        lbResultadoAluno.setText("???");
        lbRMedia.setText("???");
        lbResult.setText("???");
        Painel.setBackground(Color.gray);
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoGEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoGEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoGEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoGEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoGEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btGBoletim;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbAluno2;
    private javax.swing.JLabel lbBoletim;
    private javax.swing.JLabel lbGEscolar;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbNota1;
    private javax.swing.JLabel lbNota2;
    private javax.swing.JLabel lbNota3;
    private javax.swing.JLabel lbRAluno;
    private javax.swing.JLabel lbRMedia;
    private javax.swing.JLabel lbRNota1;
    private javax.swing.JLabel lbRNota2;
    private javax.swing.JLabel lbRNota3;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbResultadoAluno;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    // End of variables declaration//GEN-END:variables
}
